server:  port: 8082
spring:  application:    name: rating-data-services
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      defaultZone: http://localhost:8083/eureka/  instance:    hostname: localhost           
    