server:  port: 9091
spring:  application:    name: movie-catalog-services
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    serviceUrl:      defaultZone: http://localhost:8083/eureka/  instance:    hostname: localhost           
    